# Site settings
title: Chaotic Neutral
SEOTitle: Chaotic Neutral
header-img: img/home-bg.jpg
email: persephone.was.taken@gmail.com
description: "Red Bull fuelled thoughts"
keyword: ""
url: "http://p3rsephone.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     huxpro
#ptihu_username:     huxpro
github_username:     p3rsephone
twitter_username:    p3rsephone
#facebook_username:   tdosilva
reddit_username:     tdosilva



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Plugins
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Google Analytics
ga_track_id: 'UA-114214774-1'            # Format: UA-xxxxxx-xx
ga_domain: p3rsephone.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "My travels, studies, and whatever thoughts I have at 3AM when I should be asleep."
sidebar-avatar: /img/avatar-per.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Red",
        href: "https://jhugobb.github.io/"
#    },{
#        title: "Foo",
#        href: "#"
#    },{
#        title: "Bar",
#        href: "#"
#    },{
#        title: "Example Friends",
#        href: "#"
#    },{
#        title: "It helps SEO",
#        href: "#"
    }
]
